[project]
name = "pbcm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.117.1",
]

[dependency-groups]
dev = [
    "pytest>=8.4.2",
]
